# Generated by Django 5.2 on 2026-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('contractor', 'Contractor')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('wage', models.IntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
