# Generated by Django 5.2 on 2026-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='max_workers',
            field=models.IntegerField(default=1),
        ),
    ]
