# Generated by Django 5.2 on 2026-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='days',
        ),
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
