# Generated by Django 5.2 on 2026-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_days_job_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
